apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-functions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-functions
  template:
    metadata:
      labels:
        app: notifications-functions
    spec:
      containers:
        - name: notifications-functions
          image: fiapmicroservicos-notifications-functions:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: FUNCTIONS_WORKER_RUNTIME
              value: dotnet-isolated
            - name: AzureWebJobsStorage
              valueFrom:
                configMapKeyRef:
                  name: notifications-config
                  key: AzureWebJobsStorage
            - name: RabbitMQConnection
              valueFrom:
                secretKeyRef:
                  name: notifications-secret
                  key: RabbitMQConnection
            - name: WEBSITES_ENABLE_APP_SERVICE_STORAGE
              value: "false"
            - name: Redis__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: notifications-config
                  key: Redis__ConnectionString
            - name: Redis__LogStream
              valueFrom:
                configMapKeyRef:
                  name: notifications-config
                  key: Redis__LogStream
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
